sudo: required

language: python

python:
  - "3.5"
  - "3.6"
services:
  - docker
before_install:
  - docker pull landoop/kafka-lenses-dev:2.0

install:
  - python3 setup.py install
  - docker run -d -e ADV_HOST=127.0.0.1 -e EULA="https://dl.lenses.stream/d/?id=2d3c06ae-5b98-47e4-bb47-233b01f89621" --rm -p 3030:3030 -p 9092:9092 -p 2181:2181 -p 8081:8081 -p 9581:9581 -p 9582:9582 -p 9584:9584 -p 9585:9585 landoop/kafka-lenses-dev:2.0

before_script:
  - sleep 300

script:
  - python3 ./tests/test.sh
